---
language: ruby
gemfile:
  - test/support/Gemfile
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
bundler_args: --without integration
script:
  - bundle exec rake knife
  - bundle exec rake foodcritic
#  - bundle exec rake rubocop
